// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using wfa_scolaireDepart.Models;

namespace wfa_scolaireDepart.Models
{
    public partial interface Ik2fl_bdContextProcedures
    {
        Task<List<ListerResultatEtudiantResult>> ListerResultatEtudiantAsync(string no_Da, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<nombreCoursSessionResult>> nombreCoursSessionAsync(string session, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> nombreCoursSessionOutputAsync(string session, OutputParameter<int?> nombreCours, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
