// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace wfa_scolaireDepart.Models
{
    public partial class nombreCoursSessionResult
    {
        [Column("nombre de cours")]
        public int? nombredecours { get; set; }
    }
}
