// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace wfa_scolaireDepart.Models;

[Table("tbl_cours")]
public partial class TblCour
{
    [Key]
    [Column("no_cours")]
    [StringLength(8)]
    public string NoCours { get; set; }

    [Column("nom_cours")]
    [StringLength(100)]
    public string NomCours { get; set; }

    [Column("pond")]
    [StringLength(5)]
    public string Pond { get; set; }

    [InverseProperty("NoCoursNavigation")]
    public virtual ICollection<TblOffreCour> TblOffreCours { get; set; } = new List<TblOffreCour>();

    [ForeignKey("NoCoursPrealable")]
    [InverseProperty("NoCoursPrealables")]
    public virtual ICollection<TblCour> NoCoursDeBases { get; set; } = new List<TblCour>();

    [ForeignKey("NoCoursDeBase")]
    [InverseProperty("NoCoursDeBases")]
    public virtual ICollection<TblCour> NoCoursPrealables { get; set; } = new List<TblCour>();
}